name: onlywithsoul
favicon: null
layout_spectrum: 0
typography_spectrum: 0.72655
title: onlywithsoul
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#4f4f4f'
    - '#efefef'
    - '#016fde'
    - '#7b7b7b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
