name: onoywithsoul
favicon: null
layout_spectrum: 0.48956
typography_spectrum: 0.72655
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eadfdd'
    - '#e1b2a0'
    - '#69666f'
    - '#6a0800'
    - '#403d44'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
